# Use an official Grafana image as the base
FROM grafana/grafana:latest

# Optionally, copy any configuration files or provisioning files
# COPY ./path/to/your/grafana/config /etc/grafana/config

# Expose Grafana port
EXPOSE 3000

# Start Grafana
CMD ["grafana-server", "-homepath", "/usr/share/grafana"]
