{
 "title": "BigKoala Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Recent Incidents Table",
   "type": "table",
   "description": "To get the most recent incidents",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT number AS incident_number, incident_state, opened_at, resolved_at, assigned_to, priority FROM incident_event.incidents ORDER BY opened_at DESC LIMIT 20 "
    }
   ]
  },
  {
   "title": "Resolution time (in minutes)",
   "type": "barchart",
   "description": "To show incidents and whether they met SLA targets",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    number AS incident_number, \r\n    TIMESTAMPDIFF(MINUTE, opened_at, resolved_at) AS resolution_time\r\nFROM \r\n    incidents\r\nWHERE \r\n    incident_state = 'Closed'\r\nORDER BY \r\n    incident_number DESC\r\nLIMIT 15;\r\n"
    }
   ]
  },
  {
   "title": "Incident Count by Priority",
   "type": "stat",
   "description": "To get a breakdown of incidents by priority",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    priority, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nGROUP BY \r\n    priority\r\nORDER BY \r\n    priority DESC;\r\n"
    }
   ]
  },
  {
   "title": "Incident Resolution Time (in hours)",
   "type": "stat",
   "description": "To calculate the average resolution time for incidents ordered by priority levels ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    priority,\r\n    AVG(TIMESTAMPDIFF(HOUR, opened_at, resolved_at)) AS avg_resolution_time\r\nFROM \r\n    incidents\r\nWHERE \r\n    resolved_at IS NOT NULL \r\n    AND opened_at IS NOT NULL\r\n    AND active = 'Closed'\r\nGROUP BY \r\n    priority\r\nORDER BY \r\n    priority;\r\n"
    }
   ]
  },
  {
   "title": "Incidents by Hour of Day",
   "type": "barchart",
   "description": "This bar char shows the incidents per the hour of the day spanning the three months from our data",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    DATE_FORMAT(opened_at, '%H:00') AS hour_of_day, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nGROUP BY \r\n    hour_of_day\r\nORDER BY \r\n    hour_of_day;"
    }
   ]
  },
  {
   "title": "Trend Analysis",
   "type": "timeseries",
   "description": "To visualize trends over time, you can use a query like this to get incidents by day",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    DATE(opened_at) AS date, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nGROUP BY \r\n    date\r\nORDER BY \r\n    date;\r\n"
    }
   ]
  },
  {
   "title": "Incidents by Day of the Week",
   "type": "barchart",
   "description": "To visualize the frequency of incidents over different days of the week",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    DAYNAME(opened_at) AS day_of_week, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nGROUP BY \r\n    day_of_week\r\nORDER BY \r\n    FIELD(day_of_week, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');\r\n"
    }
   ]
  },
  {
   "title": "Incident Count per Assigned Group",
   "type": "table",
   "description": "To analyze incidents based on the assigned group to resolve the incident",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    assignment_group AS incident_group, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nWHERE \r\n    assignment_group IS NOT NULL \r\n    AND assignment_group != ''\r\n    AND assignment_group != '?'\r\nGROUP BY \r\n    assignment_group\r\nORDER BY \r\n    incident_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Incident Count per Mnemonic Group",
   "type": "table",
   "description": "To view incidents categorized by their mnemonic group",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "dataset": "incident_event",
     "rawSql": "SELECT \r\n    category AS mnemonic, \r\n    COUNT(*) AS incident_count\r\nFROM \r\n    incidents\r\nGROUP BY \r\n    category\r\nORDER BY \r\n    incident_count DESC;\r\n"
    }
   ]
  }
 ]
}