CREATE DATABASE IF NOT EXISTS incident_event;
USE incident_event;

CREATE TABLE IF NOT EXISTS incidents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(255),
    incident_state VARCHAR(255),
    active BOOLEAN,
    reassignment_count INT,
    reopen_count INT,
    sys_mod_count INT,
    made_sla BOOLEAN,
    caller_id VARCHAR(255),
    opened_by VARCHAR(255),
    opened_at DATETIME,
    sys_created_by VARCHAR(255),
    sys_created_at DATETIME,
    sys_updated_by VARCHAR(255),
    sys_updated_at DATETIME,
    contact_type VARCHAR(255),
    location VARCHAR(255),
    category VARCHAR(255),
    subcategory VARCHAR(255),
    u_symptom VARCHAR(255),
    cmdb_ci VARCHAR(255),
    impact VARCHAR(255),
    urgency VARCHAR(255),
    priority VARCHAR(255),
    assignment_group VARCHAR(255),
    assigned_to VARCHAR(255),
    knowledge BOOLEAN,
    u_priority_confirmation BOOLEAN,
    notify VARCHAR(255),
    problem_id VARCHAR(255),
    rfc VARCHAR(255),
    vendor VARCHAR(255),
    caused_by VARCHAR(255),
    closed_code VARCHAR(255),
    resolved_by VARCHAR(255),
    resolved_at DATETIME,
    closed_at DATETIME
);
